const char* Css =
"body     { font-family:'Segoe UI', Calibri, Arial, sans-serif; margin-left:10em; line-height:1.1em; padding:0; border:0; }\r\n"
"h1       { color:darkblue; font-size:150%; font-weight:normal; margin-bottom:0pt; }\r\n"
"h2       { color:blue; font-size:130%; font-weight:normal; margin-bottom:0pt; }\r\n"
"h3       { color:green; font-size:120%; font-weight:normal; margin-bottom:0pt; }\r\n"
".command { font-size:80%; color:green; }\r\n"
"a        { text-decoration:none; }\r\n"
"form     { font: inherit;  line-height:1.2em; }\r\n"
"code     { font-family:'Courier New', Courier, monospace; white-space:pre; font-size:100%; line-height:inherit;}\r\n"
"textarea { font-family:'Courier New', Courier, monospace; white-space:pre; font-size:100%; line-height:inherit;}\r\n"
"input[value=Submit] { vertical-align:top; }\r\n"
"input[value=Clear]  { vertical-align:top; }\r\n"
"input[type=textbox] {font-family:'Segoe UI', Calibri, Arial, sans-serif; font-size:100%; border:none gray; margin:0; padding:0; color:DarkBlue;}\r\n"
".leftcol    { float:left; width:30%; margin-right:1%; margin-bottom:1%; padding:0pt; }\r\n"
".rightcol   { margin-left:31%; }\r\n"
".nocol      { clear:left; }\r\n"
".col1   { float: left; width:  1em; }\r\n"
".col2   { float: left; width:  2em; }\r\n"
".col3   { float: left; width:  3em; }\r\n"
".col4   { float: left; width:  4em; }\r\n"
".col5   { float: left; width:  5em; }\r\n"
".col6   { float: left; width:  6em; }\r\n"
".col7   { float: left; width:  7em; }\r\n"
".col8   { float: left; width:  8em; }\r\n"
".col9   { float: left; width:  9em; }\r\n"
".col10  { float: left; width: 10em; }\r\n"
".col11  { float: left; width: 11em; }\r\n"
".col12  { float: left; width: 12em; }\r\n"
".col13  { float: left; width: 13em; }\r\n"
".col14  { float: left; width: 14em; }\r\n"
".col15  { float: left; width: 15em; }\r\n"
".col16  { float: left; width: 16em; }\r\n"
".col17  { float: left; width: 17em; }\r\n"
".col18  { float: left; width: 18em; }\r\n"
".col19  { float: left; width: 19em; }\r\n"
".col20  { float: left; width: 20em; }\r\n"
".col21  { float: left; width: 21em; }\r\n"
".col22  { float: left; width: 22em; }\r\n"
".col23  { float: left; width: 23em; }\r\n"
".col24  { float: left; width: 24em; }\r\n"
".col25  { float: left; width: 25em; }\r\n"
".col26  { float: left; width: 26em; }\r\n"
".col27  { float: left; width: 27em; }\r\n"
".col28  { float: left; width: 28em; }\r\n"
".col29  { float: left; width: 29em; }\r\n"
".col30  { float: left; width: 30em; }\r\n"
"\r\n"
"nav ul            { list-style-type:none; margin:0; padding:0; overflow:hidden; position:fixed; top:0; left:0; width:8em; font-size:1.2em; }\r\n"
"nav ul li         { background:lightskyblue; padding:0; border-style:none; margin:0.2em; }\r\n"
"nav ul li.this    { background:coral; }\r\n"
"nav ul li a       { display:block; color:black; text-decoration:none; border:0;margin:0; padding:0.5em; }\r\n"
"nav ul li a:hover { color:DarkRed; }\r\n"
"\r\n"
"span.header  { color:Black; font-weight:bold; }\r\n"
"span.online  { color:DarkSlateGray; }\r\n"
"span.offline { color:Silver; }\r\n";

const char* CssDate = __DATE__;
const char* CssTime = __TIME__;
